---
title: "Lab 00 - Hello IDS!"
author: "Ivy Mowete"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Manya", "Fola", "Jacob", 
           "Doga", "Seyara"),
  github_username = c( "manya-1", "fola-ed", "3w3w3w", "Doga2424", 
                      "seyara-g"), 
  colour = c("blue", "red", "red", 
             "red", "blue"),
  hobby = c("football", "basketball", "swimming", 
            "piano", "music"),
  favourite_number = c(10, 6, 7, 6, 7)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```


* The data that we collected in the tutorial plotted on a bar graph *

### Exercises 19

Change the text of the plot title and axis labels.

```{r labelled-bar-plot}
p1 + labs(x = "Name", 
          y = "Colour",
          title = "Favourite Colour")
```

* labs command puts the x and y axis of the graph and the title *

### Exercise 20

```{r new-bar-plot}
p2 <- ggplot(team_data, aes(x = hobby)) +
  geom_bar()
p2
```

*.*
